version: "3.8"
services:
    cache:
        image: redis:7.0-alpine
        restart: always
        ports:
            - "6379:6379"
        # redis-cli -a eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        command: redis-server --save 20 1 --loglevel verbose --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes:
            - cache:/data
volumes:
    cache:
        driver: local
